name: weaviate_backup
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  backup:
    runs-on: ubuntu-latest
    outputs:
      backup_id: ${{ steps.backup_script.outputs.WBKID }}
      result: ${{ steps.backup_script.outputs.result }}
    steps:
      - name: Execute curl command 
        id: backup_script
        run: | 
          echo "Running the script"
          echo "WBKID=$(date +%d-%m-%Y_%H-%M-%S)"  >> "$GITHUB_OUTPUT"
          echo "result=$(curl --location --request GET 'https://4ca5-103-201-151-237.ngrok-free.app' \
          --header 'Content-Type: application/json' \
          --data '{
            "loader": "web_base_loader",
            "loader_options": {"url": "https://help.hellotars.com/en/"}
          }')" >> "$GITHUB_OUTPUT"
  report:
    needs: backup
    if: ${{ always() }} 
    runs-on: ubuntu-latest
    env:
      WBKID: ${{needs.backup.outputs.backup_id}}
      result: ${{ needs.backup.outputs.result }}
    steps:  
      - name: status report
        run: echo "Backup script with id = $WBKID and result = $result"
        
         