name: testing_and_deploying
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Caching dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: cache-dependencies-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint 
        run: npm run lint
      - name: Tests
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Deploying.."
  credentials:
    runs-on: ubuntu-latest
    env:
      key1: process.env.KEY1
      key2: process.env.KEY2
    steps:
      - name: printing creds
        run: |
          echo "$key1"
          echo "$key2"