name: issues_workflow
on: 
    issues:
      types: [opened, closed]
jobs:
    print_issue:
        runs-on: [self-hosted, Linux, X64, receive]
        steps:
            - name: print_metadata
              run: echo "${{ toJson(github) }}"